### ISSUE TITLE
Weird slowdown while importing, investigate

### ISSUE THREAD

**Issue by wires** [graphmalizer/graphmalizer-core#8]
what the subject says

**Comment by wires** [comment]
might be related to out of mem error, still unsure what causes this

```
errors":[{"code":"Neo.DatabaseError.General.UnknownFailure","message":"Java heap space","stackTrace":"java.lang.OutOfMemoryError: Java heap space
	at java.util.LinkedList.linkFirst(LinkedList.java:125)
	at java.util.LinkedList.addFirst(LinkedList.java:291)
	at org.neo4j.kernel.impl.traversal.TraversalBranchImpl.relationships(TraversalBranchImpl.java:239)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.VariableLengthGraphRelationship.relationships(GraphRelationship.scala:63)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.AddedHistory$$anonfun$relationshipIterable$1.apply(History.scala:91)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.AddedHistory$$anonfun$relationshipIterable$1.apply(History.scala:91)
	at scala.Option.map(Option.scala:145)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.AddedHistory.relationshipIterable(History.scala:91)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.AddedHistory.toSeq(History.scala:82)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.AddedHistory.toMap$lzycompute(History.scala:72)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.AddedHistory.toMap(History.scala:71)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.PatternMatcher.isMatchSoFar(PatternMatcher.scala:174)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.PatternMatcher.org$neo4j$cypher$internal$compiler$v2_2$pipes$matching$PatternMatcher$$traverseNextNodeFromRelationship(PatternMatcher.scala:110)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.PatternMatcher$$anonfun$7.apply(PatternMatcher.scala:163)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.PatternMatcher$$anonfun$7.apply(PatternMatcher.scala:163)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream.foldLeft(Stream.scala:563)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.PatternMatcher.traverseRelationship(PatternMatcher.scala:163)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.PatternMatcher.traverseNextSpecificNode(PatternMatcher.scala:75)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.PatternMatcher.traverseNode(PatternMatcher.scala:89)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.PatternMatcher.foreach(PatternMatcher.scala:40)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.to(TraversableLike.scala:629)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.PatternMatcher.to(PatternMatcher.scala:28)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.PatternMatcher.toBuffer(PatternMatcher.scala:28)
	at scala.collection.TraversableLike$class.toStream(TraversableLike.scala:624)
"}]}
recv end 173971
```

**Comment by wires** [comment]
another one

```
"errors":[{"code":"Neo.DatabaseError.General.UnknownFailure","message":"Java heap space","stackTrace":"java.lang.OutOfMemoryError: Java heap space
	at scala.collection.mutable.OpenHashMap.growTable(OpenHashMap.scala:89)
	at scala.collection.mutable.OpenHashMap.scala$collection$mutable$OpenHashMap$$put(OpenHashMap.scala:127)
	at scala.collection.mutable.OpenHashMap.put(OpenHashMap.scala:124)
	at scala.collection.mutable.OpenHashMap.$plus$eq(OpenHashMap.scala:120)
	at scala.collection.mutable.OpenHashMap.$plus$eq(OpenHashMap.scala:51)
	at org.neo4j.cypher.internal.compiler.v2_2.ExecutionContext.$plus$eq(ExecutionContext.scala:50)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.SimplePatternMatcherBuilder$$anonfun$getMatches$1$$anonfun$apply$2.apply(SimplePatternMatcherBuilder.scala:114)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.SimplePatternMatcherBuilder$$anonfun$getMatches$1$$anonfun$apply$2.apply(SimplePatternMatcherBuilder.scala:112)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:130)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.SimplePatternMatcherBuilder$$anonfun$getMatches$1.apply(SimplePatternMatcherBuilder.scala:112)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.SimplePatternMatcherBuilder$$anonfun$getMatches$1.apply(SimplePatternMatcherBuilder.scala:106)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.SimplePatternMatcherBuilder.getMatches(SimplePatternMatcherBuilder.scala:106)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.MatchingContext.getMatches(MatchingContext.scala:55)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.MatchPipe$$anonfun$internalCreateResults$1.apply(MatchPipe.scala:45)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.MatchPipe$$anonfun$internalCreateResults$1.apply(MatchPipe.scala:41)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:256)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1157)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.builders.IfElseIterator.fillBuffer(IfElseIterator.scala:62)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.builders.IfElseIterator.hasNext(IfElseIterator.scala:38)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.builders.IfElseIterator.foreach(IfElseIterator.scala:28)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
"}]}
```

**Comment by wires** [comment]
alee alee

```
  statusCode: 200,
  errors:
   [ { code: 'Neo.DatabaseError.General.UnknownFailure',
       message: 'Java heap space',
       stackTrace: 'java.lang.OutOfMemoryError: Java heap space
	at org.neo4j.graphmatching.PatternMatch.<init>(PatternMatch.java:36)
	at org.neo4j.graphmatching.PatternFinder.extractPotentialResult(PatternFinder.java:183)
	at org.neo4j.graphmatching.PatternFinder.traverseFromCallStack(PatternFinder.java:208)
	at org.neo4j.graphmatching.PatternFinder.findNextMatch(PatternFinder.java:159)
	at org.neo4j.graphmatching.PatternFinder.hasNext(PatternFinder.java:388)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.SimplePatternMatcherBuilder.getMatches(SimplePatternMatcherBuilder.scala:106)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.matching.MatchingContext.getMatches(MatchingContext.scala:55)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.MatchPipe$$anonfun$internalCreateResults$1.apply(MatchPipe.scala:45)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.MatchPipe$$anonfun$internalCreateResults$1.apply(MatchPipe.scala:41)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:256)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1157)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.builders.IfElseIterator.fillBuffer(IfElseIterator.scala:62)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.builders.IfElseIterator.hasNext(IfElseIterator.scala:38)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.builders.IfElseIterator.foreach(IfElseIterator.scala:28)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.builders.IfElseIterator.to(IfElseIterator.scala:28)
	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:257)
	at org.neo4j.cypher.internal.compiler.v2_2.executionplan.builders.IfElseIterator.toList(IfElseIterator.scala:28)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.EagerPipe.internalCreateResults(EagerPipe.scala:41)
	at org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:122)
' } ],
```

**Comment by wires** [comment]
confirmed this is due to `equivalence` queries

**Comment by wires** [comment]
(traversals would wrap arround, should check with explain query)
